spring:
  profiles:
    active: prod  # 배포 환경

  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration  # ← 추가
      - org.springframework.ai.model.openai.autoconfigure.OpenAiModerationAutoConfiguration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        enabled: false
      embedding:
        enabled: false
      image:
        enabled: false
      moderation:
        enabled: false
      transcription:
        enabled: false     # ← 추가 (에러 메시지의 경로와 동일)
      audio:
        speech:
          enabled: false
        transcription:
          enabled: false   # ← 혹시 모를 구버전 경로도 함께 차단

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.fork.app: INFO

jwt:
  secret: ${JWT_SECRET_KEY}
  expirationMs: 3600000

file:
  upload-dir: /path/to/uploads

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false

kakao:
  api:
    key: ${KAKAO_API_KEY}

chatbot:
  enabled: false
