name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image (skip tests)
        run: |
          IMAGE=ghcr.io/FORK-FE-BE/FORK-BE:latest
          ./gradlew bootJar -x test
          docker build -t $IMAGE .

      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/FORK-FE-BE/FORK-BE:latest
          docker push $IMAGE
